[build-system]
requires = ["setuptools >= 77.0.3", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[project]
name = "LE_pkg"
dynamic = ["version"]
description = "A python package that simulate Light Echo images"
requires-python = ">=3.10"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Tatiana Acero-Cuellar", email = "taceroc@udel.edu"}
]

classifiers = [
  "Development Status :: 4 - Beta"
]


dependencies = [
            numpy = "*"
            scipy = "*"
            pandas = "*"
            matplotlib = "*"
            astropy = "*"
            pyyaml = "*"
]


